#!/bin/bash -
#
# Copyright (c) 2017 - Adjacent Link LLC, Bridgewater, New Jersey
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# * Redistributions of source code must retain the above copyright
#   notice, this list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in
#   the documentation and/or other materials provided with the
#   distribution.
# * Neither the name of Adjacent Link LLC nor the names of its
#   contributors may be used to endorse or promote products derived
#   from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
<%
import re
net_devs = set()
for key in context.keys():
    if re.match(r'lxc.interface\.(\d+)\.name',key) and context[key] != 'lo':
       net_devs.add(context[key])
%>

start_sshd()
{
    local pidfile=$1

    /usr/sbin/sshd -o "PidFile=$pidfile"
}

export PATH=$PATH:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin

top_dir=$1
node=$2
env=$3
start_utc=$4

# fix devpts
mount /dev/pts -o remount,rw,mode=620,ptmxmode=666,gid=5

# turn on forwarding
sysctl net.ipv4.ip_forward=1
sysctl net.ipv6.conf.all.forwarding=1

# disable tx and rx checksum offloading
% for net_dev in net_devs:
ethtool --offload  ${net_dev} rx off tx off
% endfor

# source in an environment if provided
if [ -n "$env" ]
then
    . $env
fi

# start sshd
start_sshd $top_dir/persist/$node/var/run/ssh.pid

# run a local init if provided
if [ -f $top_dir/$node/init.local ]
then
    bash $top_dir/$node/init.local "$top_dir" "$node" "$start_utc" \
       2>&1 | tee  $top_dir/persist/$node/var/log/init.log
fi
